apiVersion: v1
kind: Service
metadata:
  name: menu
  labels:
    app: menu
    service: menu
spec:
  type: ClusterIP
  selector:
    app: menu
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
